version: '3.7'
services:
  clusdoc:
    build:
      context: ${CLUSDOC_CONTEXT-../}
      dockerfile: ${CLUSDOC_DOCKERFILE-./build/Dockerfile}
      target: prod
    image: clusdoc
    container_name: clusdoc
    ports:
      - ${CLUSDOC_PORT-8004}:80
    env_file: ${CLUSDOC_ENV-.env}
