version: '3.7'
services:
  clusdoc:
    build:
      context: ${CLUSDOC_CONTEXT-../}
      dockerfile: ${CLUSDOC_DOCKERFILE-./build/Dockerfile}
      target: dev
    image: ${CLUSDOC_IMAGE-clusdoc:dev}
    container_name: ${CLUSDOC_CONTAINER-clusdoc-dev}
    ports:
      - ${CLUSDOC_PORT-8004}:8004
    volumes:
      - ${CLUSDOC_CONTEXT-../}:/app/clusdoc/
