version: '3.7'
services:
  clusdoc:
    build:
      context: ${CLUSDOC_CONTEXT-../}
      dockerfile: ${CLUSDOC_DOCKERFILE-./build/Dockerfile}
      target: prod
    image: ${CLUSDOC_IMAGE-clusdoc}
    container_name: ${CLUSDOC_CONTAINER-clusdoc}
    ports:
      - ${CLUSDOC_PORT-8004}:80
