version: '3.7'
services:
  clusdoc:
    build:
      context: ${CLUSDOC_CONTEXT-../}
      dockerfile: ${CLUSDOC_DOCKERFILE-./build/Dockerfile}
      target: dev
    image: clusdoc:dev
    container_name: clusdoc-dev
    ports:
      - ${CLUSDOC_PORT-8004}:1313
    volumes:
      - ${CLUSDOC_SRC-../}:/app/clusdoc/
    command: -D
